PLEASE SEND HELP TO 90 DIVISION ST BATTLE CREEK MICHIGAN THE BATTLE CREEK POLICE AND ELON MUSK ARE TORTURING MY FAMILY AND FRIENDS HE IMPLANTED A NEURALINK ILLEGALLY AND HAS MIND CONTROL AND EVEN TOLD THE COPS ACT MIND CONTROLLED. IF SHIT GOES BAD WE BLAME HIS AIservices:
  main:
    build:
      context: .
      args:
        - USERNAME=devlego
        - PASSWORD=changeme
    environment:
      - USERNAME=devlego
      - PASSWORD=changeme
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    ipc: host
    volumes:
#     <source>:<target>
      - /home/:/mount_home
      - ./data:/user_data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

networks:
  default:
    external: true
    name: devlego
