export CODE_SERVER_VERSION="4.96.0" # https://github.com/cdr/code-server/releases (Latest as of Apr 2025)
export TTYD_VERSION="1.7.8" # https://github.com/tsl0922/ttyd/releases (Latest as of Apr 2025)
export WEBWORMHOLE_VERSION="latest" # https://github.com/pojntfx/webwormhole-binaries/releases/tag/latest (Keeping "latest" as requested)
export CMAKE_FORMAT_EXTENSION_VERSION="0.7.0" # https://github.com/cheshirekow/cmake_format/releases (Latest as of Apr 2025)
export GO_VERSION="1.24.2" # https://golang.org/dl/ (Latest stable as of Apr 2025)
export TINYGO_VERSION="0.34.0" # https://github.com/tinygo-org/tinygo/releases (No newer release found as of Apr 2025)
export TINYGO_EXTENSION_VERSION="0.5.0" # https://github.com/tinygo-org/vscode-tinygo/releases (No newer release found as of Apr 2025)
export JAVA_JUPYTER_VERSION="1.3.0" # https://github.com/SpencerPark/IJava/releases (No newer release found as of Apr 2025)
export JULIA_MAJOR_VERSION="1.11" # https://julialang.org/downloads/#current_stable_release (Latest stable branch as of Apr 2025)
export JULIA_MINOR_VERSION="4" # https://julialang.org/downloads/#current_stable_release (Latest patch for 1.11 as of Apr 2025)
export OCTAVE_HACKING_EXTENSION_VERSION="0.2.14" # https://github.com/apjanke/vscode-octave-hacking/releases (No newer release found as of Apr 2025)
export OCTAVE_EXTENSION_VERSION="0.0.3" # https://marketplace.visualstudio.com/items?itemName=toasty-technologies.octave (No newer release found as of Apr 2025)
export OCTAVE_DEBUGGER_VERSION="0.4.20" # https://marketplace.visualstudio.com/items?itemName=paulosilva.vsc-octave-debugger (No newer release found as of Apr 2025)
export K9S_VERSION="v0.32.6" # https://github.com/derailed/k9s/releases (No newer release found as of Apr 2025, added 'v' prefix for consistency with tags)
export AERC_VERSION="latest" # https://github.com/pojntfx/aerc-binaries/releases (Keeping "latest" as requested)
export GRPCURL_VERSION="1.9.1" # https://github.com/fullstorydev/grpcurl/releases (No newer release found as of Apr 2025)
export WEB_ACCESSIBILITY_EXTENSION_VERSION="0.2.83" # https://marketplace.visualstudio.com/items?itemName=MaxvanderSchee.web-accessibility (No newer release found as of Apr 2025)
export APOLLO_EXTENSION_VERSION="1.19.4" # https://marketplace.visualstudio.com/items?itemName=apollographql.vscode-apollo (No newer release found as of Apr 2025)
export VIM_EXTENSION_VERSION="1.28.1" # https://open-vsx.org/extension/vscodevim/vim (Latest as of Apr 2025)
export POWERSHELL_EXTENSION_VERSION="2024.4.0" # https://github.com/PowerShell/vscode-powershell/releases (No newer release found as of Apr 2025)
export SCSS_EXTENSION_VERSION="0.10.0" # https://github.com/mrmlnc/vscode-scss/releases (No newer release found as of Apr 2025)
